# Generated by Django 6.0.1 on 2026-02-02 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE app_users 
            ADD COLUMN email VARCHAR(255) UNIQUE NOT NULL DEFAULT 'temp@example.com';
            
            ALTER TABLE app_users 
            ALTER COLUMN email DROP DEFAULT;
            """,
            reverse_sql="""
            ALTER TABLE app_users
            DROP COLUMN email;
            """
        )
    ]
